@echo off
cd /d "%~dp0"
echo Creating virtual environment...
python -m venv venv
echo Activating venv...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install fastapi uvicorn pydantic selenium webdriver-manager
echo Starting server...
python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
pause
